# vim: set ts=2 sw=2 expandtab ai:

version: '3'
volumes:
  jenkins_home:
    external: true
services:
  jenkins:
    build: .
    volumes:
      - jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
